// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygigsgtnaabmimpgaufa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnaWdzZ3RuYWFibWltcGdhdWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTA2NzEsImV4cCI6MjA2MTA4NjY3MX0.OgGr1UVTCzpTjagbTPB5Q4kYzI9ygIPSTfODJDIMgzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);